### ISSUE TITLE
doomsday job is failing 

### ISSUE THREAD

**Issue by aashishborase** [doomsday-project/doomsday-boshrelease#2]
Hello team,
I am trying to deploy doomsday v0.8.1 but doomsday job is failing with status (does not exists).
checked with the logs:

goroutine 33 [running]:
github.com/doomsday-project/doomsday/storage.(*ConfigServerAccessor).Get(0xc000210048, 0xc000357b00, 0x53, 0x0, 0x0, 0x0)
        /Users/tom/go_workspace/src/github.com/doomsday-project/doomsday/storage/configserver.go:140 +0x2b7
github.com/doomsday-project/doomsday/server.(*Core).populateUsing.func1()
        /Users/tom/go_workspace/src/github.com/doomsday-project/doomsday/server/core.go:94 +0x13e
created by github.com/doomsday-project/doomsday/server.(*Core).populateUsing
        /Users/tom/go_workspace/src/github.com/doomsday-project/doomsday/server/core.go:139 +0x284
Wed Jan  8 06:26:19 UTC 2020 starting up doomsday (pid 14552)
Jan  8 06:26:19: Initializing server
Jan  8 06:26:19: Configuring targeted storage backends
Jan  8 06:26:19: Configuring backend `client-bosh-credhub' of type `credhub'
Performing client credentials grant auth
Auth complete
Refreshing Credhub token every 29m59.5s
Jan  8 06:26:20: Began asynchronous cache population
Jan  8 06:26:20: Configuring frontend authentication
Jan  8 06:26:20: Notifications configured
Jan  8 06:26:20: Running scheduled populate of `client-bosh-credhub'
Jan  8 06:26:20: Beginning listening on port 8111
panic: interface conversion: interface {} is nil, not string 

could you help me with this ?

**Comment by thomasmitchell** [comment]
You have a certificate in your Credhub in which the "certificate" key is null.

Doomsday should be able to handle this more gracefully than panicking, and so I'll open this as an issue in the main project. That said, this does reflect a misconfiguration of data in your Credhub, as a certificate object without a certificate is hardly a certificate at all. I don't know which key is causing the problem though. If you clean that up or add a certificate key, this problem should go away for you.

**Comment by aashishborase** [comment]
Issue is resolved. Thanks for the help
